version: "3.9"

services:
  titiler:
    image: ghcr.io/developmentseed/titiler:latest
    container_name: titiler
    platform: linux/amd64
    # network_mode: host
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    command: uvicorn titiler.application.main:app --host 0.0.0.0 --port 8001 --workers 1

  shiny:
    build: ./shiny
    container_name: shiny
    # network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data 
    depends_on:
      - titiler
