name: shiny_app
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pandas
    - xarray
    - rioxarray
    - geopandas
    - rasterio 
    - shiny
    - ipyleaflet
    - plotly
    - pip
    - pip:
        - shinywidgets
    # - pandas
    # - numpy
    # - matplotlib
    # - folium
    # - leafmap
    # - pip:
    #     - cdsapi>=0.7.4
    #     - pycountry
    #     - netCDF4
    #     - dask
    #     - titiler.core
